trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:
  - powershell: |
      $ENV:CAKE_SKIP_GITVERSION=([string]::IsNullOrEmpty($ENV:SYSTEM_PULLREQUEST_PULLREQUESTID) -eq $False).ToString()
      .\build.ps1 --target=Buildserver
      exit $LASTEXITCODE
    displayName: 'Cake Build'
- job: macOS
  pool:
    vmImage: 'macOS-11'
  steps:
  - bash: |
      ./build.sh --target=Buildserver
    displayName: 'Cake Build'
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: |
      ./build.sh --target=Buildserver
    displayName: 'Cake Build'